### PR TITLE
Update Aff dependency

### PR DESCRIPTION
**Pull request by garyb**

### CODE REVIEW

**Comment by paf31** [comment]
Thanks! So this becomes 2.0.0 now, right?

**Comment by garyb** [comment]
Yeah, unfortuately - just noticed I didn't commit `src` though, which is why the build is failing. I'll fix that now!

**Comment by paf31** [comment]
👍 LGTM

**Comment by garyb** [comment]
Now I need to update the test :smile:

I'll merge/release once I get travis to pass... you've seen the actual change at least!

**Pull request merged**
